Update Scrum example to use UseWebApi(this IAppBuilder builder, HttpServer httpServer) instead of UseWebApi(this IAppBuilder builder, HttpConfiguration configuration)   (2 other examples were already correct).
This avoids the error:

```
Error  	LogJam.WebApi.LogJamExceptionLogger                    Exception thrown handling Web API request: POST http://localhost:40505/odata/%24batch
System.ArgumentException: The 'DelegatingHandler' list is invalid because the property 'InnerHandler' of 'RequestMessageHandlerTracer' is not null.
Parameter name: handlers
   at System.Net.Http.HttpClientFactory.CreatePipeline(HttpMessageHandler innerHandler, IEnumerable`1 handlers)
   at System.Web.Http.HttpServer.Initialize()
   at System.Web.Http.HttpServer.<EnsureInitialized>b__b()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at System.Web.Http.HttpServer.EnsureInitialized()
   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EntityRepository.ODataServer.Batch.BatchChangeSetRequestItem.<SendSubRequestAsync>d__9.MoveNext() in c:\devtools\teamcity\BuildAgent\work\a1dac9440314bb7\src\ODataServer\Batch\BatchChangeSetRequestItem.cs:line 105
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at EntityRepository.ODataServer.Batch.BatchChangeSetRequestItem.<SendRequestAsync>d__0.MoveNext() in c:\devtools\teamcity\BuildAgent\work\a1dac9440314bb7\src\ODataServer\Batch\BatchChangeSetRequestItem.cs:line 91
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.OData.Batch.DefaultODataBatchHandler.<ExecuteRequestMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.OData.Batch.DefaultODataBatchHandler.<ProcessBatchAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Batch.HttpBatchHandler.<SendAsync>d__0.MoveNext()
The thread 0x3104 has exited with code 259 (0x103).
Error  	System.Web.Http.Request                                27: End
    (exception already logged)
Error  	LogJam.WebApi.LogJamExceptionLogger                    Exception thrown handling Web API request: POST http://localhost:40505/odata/%24batch
```